### ISSUE TITLE
navigation shortcut in goland

### ISSUE THREAD

**Issue by pxsa** [tsawler/bookings#3]
Hello, I'm one of your student from your Udemy course([Building modern web applications in Go](https://www.udemy.com/course/building-modern-web-applications-with-go/?referralCode=0415FB906223F10C6800)), Which shortcut do you use to open this popup?!

![Screenshot from 2023-06-22 18-22-54](https://github.com/tsawler/bookings/assets/115137933/a340a8a7-b050-4ef5-99f5-98e3f5b0275d)

**Comment by tsawler** [comment]
That's a Goland shortcut -- on a Mac it's Command-P. You get a similar popup in VS Code, but it looks a bit different. It does the same thing, though.
I may have set the shortcut to this manually at some point in the distant past, but I don't think so...

**Comment by tsawler** [comment]
The command is also Command-P in VS Code (probably CTRL-P on Windows).

**Comment by pxsa** [comment]
Thanks for your quick reply, according to this  [link](https://stackoverflow.com/questions/59094303/is-there-an-equivalent-to-vscodes-quick-open-ctrlp-in-jetbrains-ides/59094845#59094845) it's actually <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd> on Linux.
